### ISSUE TITLE
运行出现问题

### ISSUE THREAD

**Issue by lucklover** [Echowxsy/CMPEDUDownload#14]
我试着运行了以下. 但是编译器给了异常. 因为是小白,不太看得懂到底是哪里的问题. 求解答. 下面是异常提示.还想吐槽一点.大哥你代码注解太少了. 小白看不懂. 不知道从哪里开始排错.

[Traceback (most recent call last):
  File "C:\Users\zhulu\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\zhulu\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\zhulu\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\lib\python\new_ptvsd\no_wheels\ptvsd\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\zhulu\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\lib\python\new_ptvsd\no_wheels\ptvsd/..\ptvsd\server\cli.py", line 361, in main
    run()
  File "c:\Users\zhulu\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\lib\python\new_ptvsd\no_wheels\ptvsd/..\ptvsd\server\cli.py", line 203, in run_file
    runpy.run_path(options.target, run_name="__main__")
  File "C:\Users\zhulu\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\zhulu\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\zhulu\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "d:\projects\CMPEDUDownload\download.py", line 60, in <module>
    main()
  File "d:\projects\CMPEDUDownload\download.py", line 52, in main
    for pdf_link, filename in get_books(category_code):
  File "d:\projects\CMPEDUDownload\download.py", line 20, in get_books
    books = response.json()["module"]
  File "C:\Users\zhulu\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\zhulu\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\zhulu\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\zhulu\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)](url)

**Comment by echowxsy** [comment]
貌似是` books = response.json()["module"]`这里出现问题，返回内容json化失败。
我在代码里面加上注释和输出吧。

**Comment by lucklover** [comment]
> response.json()["module"]

谢谢,大佬. 等着你的新程序.

**Comment by echowxsy** [comment]
已经更新了，服务器暂时关闭，所以没有数据返回。

**Comment by bajins** [comment]
> 已经更新了，服务器暂时关闭，所以没有数据返回。

[https://github.com/woytu/reptile-python/blob/fe8e0b89470a85970290fbcb228a278222fed777/cmpedu.py#L190-L245](https://github.com/woytu/reptile-python/blob/fe8e0b89470a85970290fbcb228a278222fed777/cmpedu.py#L190-L245)

**Comment by Echowxsy** [comment]
> https://github.com/woytu/reptile-python/blob/fe8e0b89470a85970290fbcb228a278222fed777/cmpedu.py#L190-L245

尝试了一下，返回：
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>202026F2411DD66B</RequestId><HostId>PlDqJU/rIeV2eOIJJiOBfuzi0fdG8PMRZwkJDCJa0iQ23WbDFFDcY5zL42MZzRZpY0KDKv36Um8=</HostId></Error>
```
等服务器再次开放吧

**Comment by echowxsy** [comment]
> > 已经更新了，服务器暂时关闭，所以没有数据返回。
> 
> https://github.com/woytu/reptile-python/blob/fe8e0b89470a85970290fbcb228a278222fed777/cmpedu.py#L190-L245

返回403，等服务器再次开放吧。

有人已经下载了全部书籍，上传了百度云，我没有验证是否正确。

**Comment by crosslife** [comment]
> 已经更新了，服务器暂时关闭，所以没有数据返回。

求个链接~

**Comment by crosslife** [comment]
> > > 已经更新了，服务器暂时关闭，所以没有数据返回。
> > 
> > 
> > https://github.com/woytu/reptile-python/blob/fe8e0b89470a85970290fbcb228a278222fed777/cmpedu.py#L190-L245
> 
> 返回403，等服务器再次开放吧。
> 
> 有人已经下载了全部书籍，上传了百度云，我没有验证是否正确。

求个链接~

**Comment by bajins** [comment]
> > > > 已经更新了，服务器暂时关闭，所以没有数据返回。
> > > 
> > > 
> > > https://github.com/woytu/reptile-python/blob/fe8e0b89470a85970290fbcb228a278222fed777/cmpedu.py#L190-L245
> > 
> > 
> > 返回403，等服务器再次开放吧。
> > 有人已经下载了全部书籍，上传了百度云，我没有验证是否正确。
> 
> 求个链接~

https://github.com/yqylh/-Reptile

**Comment by crosslife** [comment]
> > > > > 已经更新了，服务器暂时关闭，所以没有数据返回。
> > > > 
> > > > 
> > > > https://github.com/woytu/reptile-python/blob/fe8e0b89470a85970290fbcb228a278222fed777/cmpedu.py#L190-L245
> > > 
> > > 
> > > 返回403，等服务器再次开放吧。
> > > 有人已经下载了全部书籍，上传了百度云，我没有验证是否正确。
> > 
> > 
> > 求个链接~
> 
> https://github.com/yqylh/-Reptile

感谢，不过来晚了，里面链接全挂了

**Comment by bajins** [comment]
> > > > > > 已经更新了，服务器暂时关闭，所以没有数据返回。
> > > > > 
> > > > > 
> > > > > https://github.com/woytu/reptile-python/blob/fe8e0b89470a85970290fbcb228a278222fed777/cmpedu.py#L190-L245
> > > > 
> > > > 
> > > > 返回403，等服务器再次开放吧。
> > > > 有人已经下载了全部书籍，上传了百度云，我没有验证是否正确。
> > > 
> > > 
> > > 求个链接~
> > 
> > 
> > https://github.com/yqylh/-Reptile
> 
> 感谢，不过来晚了，里面链接全挂了

看这里 https://yinkss-my.sharepoint.com/:f:/g/personal/claer_simplove_eu_org/EpzegyPPbiFPpOt5as1chqcB7fcRzJjzbzvXb16vqLQnZA    file/Books目录  剩余的还在下载，非常缓慢
