### ISSUE TITLE
Windows 下读取 json 报错

### ISSUE THREAD

**Issue by ghost** [Echowxsy/CMPEDUDownload#5]
```cmd
Traceback (most recent call last):
....
  File "d:\Users\xxxx\GitWorks\2\CMPEDUDownload\download.py", line 51, in <module>
    main()
  File "d:\Users\xxxx\GitWorks\2\CMPEDUDownload\download.py", line 39, in main
    catgories = json.load(fp)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 20: illegal multibyte sequence
```

看起来是读取 json 编码错误引起的

推荐把 

https://github.com/Echowxsy/CMPEDUDownload/blob/0752ec0b15bdd5612077800b87ebfc9da609cd3f/download.py#L38

改为
```
with open("categories.json", encoding='utf-8') as fp:
```

**Comment by echowxsy** [comment]
good
